### PR TITLE
Added arm64 support for all OS fixes issue #46

### PR DESCRIPTION
**Pull request by ashique-perumbavoor**
I have also added targets option as below:
```
    targets:
      - linux_amd64
      - linux_arm64
      - linux_386
      - windows_amd64
      - windows_arm64
      - windows_386
      - darwin_amd64
      - darwin_arm64
```
Removing the unwanted os configuration will stop making it's binaries

### CODE REVIEW

**Comment by athul** [comment]
Hey, sorry for the late comment. You should also update the `RELEASE_BUILDS` variable in the `env` key of the yml file. Also I wanted to switch the whole build from travis to GitHub actions. If you could do that too, it would be a lot easier

**Review by athul — CHANGES_REQUESTED** [review]
As mentioned in the PR comment

**Comment by BRO3886** [comment]
> Hey, sorry for the late comment. You should also update the `RELEASE_BUILDS` variable in the `env` key of the yml file. Also I wanted to switch the whole build from travis to GitHub actions. If you could do that too, it would be a lot easier

@athul what do you want to add on `RELEASE_BUILDS` env?

**Comment by athul** [comment]
I guess this can be closed due to #49

**Pull request closed without merging**
