### PR TITLE
[Refactor] Send Method

### PR DESCRIPTION
**Pull request by athul**
Fixes:
- [x] POST Requests are sent with Full Body
- [x] Add Support Parsing from Folders
- [x] Moved from Functions to Struct Methods
- [x] Refactor approach on `send` method
- [x] Document Code

Tick == Completed

### CODE REVIEW

**Comment by athul** [comment]
This will be able to fix #19 😜

**Review by liyasthomas — APPROVED** [review]
Sed aaki.

**Comment by athul** [comment]
Njan ithavana onnum cheythilla... Cheyyunathelum nallathaayikotte

**Comment by athul** [comment]
Repo il Label koodi

**Pull request merged**
